name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile generic resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Swebert_Correa_Resume.tex
      - name: Compile systems resume
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: systems/Swebert_Correa_Resume.tex
      - name: Compile ml resume
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: ml/Swebert_Correa_Resume.tex

      - name: Upload generic resume
        uses: actions/upload-artifact@v4
        with:
          name: Generic
          path: Swebert_Correa_Resume.pdf
      - name: Upload systems resume
        uses: actions/upload-artifact@v4
        with:
          name: Systems
          path: systems/Swebert_Correa_Resume.pdf
      - name: Upload ml resume
        uses: actions/upload-artifact@v4
        with:
          name: ML
          path: ml/Swebert_Correa_Resume.pdf

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: .
          GIT_CONFIG_NAME: Swebert Correa
          GIT_CONFIG_EMAIL: correaswebert@gmail.com
