name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resume_type:
          - generic
          - systems
          - ml
          - networks
          - backend
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.resume_type }}/Swebert_Correa_Resume.tex
          work_in_root_file_dir: true

      - name: Upload compiled resume
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.resume_type }}
          path: ${{ matrix.resume_type }}/Swebert_Correa_Resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: .
          GIT_CONFIG_NAME: Swebert Correa
          GIT_CONFIG_EMAIL: correaswebert@gmail.com
